// <auto-generated />
namespace PPI.Core.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class StartingToAddEventsForAMSA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartingToAddEventsForAMSA));
        
        string IMigrationMetadata.Id
        {
            get { return "201610202042549_StartingToAddEventsForAMSA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
