// <auto-generated />
namespace PPI.Core.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AMSACodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AMSACodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011425513_AMSACodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
